### ISSUE TITLE
Notes from Review:

### ISSUE THREAD

**Issue by theryankelly** [MAPC/living-little-staging#53]
- [x] Hero text needs spacing. Might need to shorten the text. could go with the original XD text and not word and move About link to a new location. See #63 
- [x] Table of final images needed. @theryankelly will make in LL Airtable See #54 
- [x] Videos added below housing type overview section
- [x] Links and thumbnails needed for videos See #58 
- [x] Need short description of videos and video titles  See #58 
- [x] Full button for selection of housing types needed. Adjustments made to XD to help describe.
- [x] Spacing and weight adjustment of the font in dropdown needed. "Explore" move to condense and given more white space
- [x] Gray text on the Gray background of sections looks off. More contrast needed
- [x] Title overlap with the yellow highlight is not as same as XD. I am ok, I think the underling of yellow works ok.
- [x] The size of example images looks off. In addition to finalizing images, we should stick to a bounding box size for all. Example added to XD. Moved to #59 
- [x] Remove bullets from call-out boxes. Example added to XD using indent and adding "?" icon instead to increase legibility and whitespace.
- [x] Should match corner box styling between white and blue boxes. XD has slightly rounded corners and drop shadows
- [x] #66

**Comment by theryankelly** [comment]
MetroCommon x 2050
DataCommon
Massbuilds
Zoning Atlas
Trailmap

**Comment by theryankelly** [comment]
Closing out issue as notes have been resolved or moved to new issues.
